file_format: "1"
id: untitled
name: untitled
type: shield
url: https://github.com/AnthonyAmanse/untitled-keyboard
requires: [nice_nano_v2]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - untitled_left
  - untitled_right
